development:
    access_key_id: AKIAIBONHGGIAHCKIJLA
    secret_access_key: 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
    bucket: 'www.mytravelcharter.com-development'
production:
    access_key_id: AKIAIBONHGGIAHCKIJLA
    secret_access_key: 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
    bucket: 'www.mytravelcharter.com-production'